name: $(date +"%Y%m%d").$(rev)

on:
  push:
    branches:
      - develop
      - release

env:
  SOURCE_DIR: ${{ github.workspace }}
  BUILD_DIR: ${{ github.workspace }}/build
  INSTALL_DIR: ${{ github.workspace }}/roadrunner-${{ runner.os }}
  LLVM_INSTALL_PREFIX: ${{ github.workspace }}/llvm
  DEPS_INSTALL_PREFIX: ${{ github.workspace }}/libroadrunner-deps
  SWIG_SOURCE_DIR: ${{ github.workspace }}/swig
  SWIG_INSTALL_PREFIX: ${{ github.workspace }}/swig/install-azure
  SWIG_EXECUTABLE: ${{ github.workspace }}/swig/install-azure/bin/swig


jobs:
  WindowsBuildRoadrunnerCpp:
    runs-on: windows-latest

    env:
      LLVM_CACHE: 'false'
      MinicondaRoot: 'C:\\Miniconda'
      PythonName: 'py39'
      PythonVersion: '3.9'
      PythonRoot: '$(MinicondaRoot)\\envs\\$(PythonName)'
      PythonLibDir: '$(PythonRoot)\\Lib'
      PythonScriptsDir: '$(PythonRoot)\\Scripts'
      PythonExecutable: '$(PythonRoot)\\python.exe'
      PipExecutable: '$(PythonScriptsDir)\\pip.exe'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Print Environment Variables
        shell: pwsh
        run: |
          echo "LLVM_CACHE=${env:LLVM_CACHE}"
          echo "PythonName=${env:PythonName}"
          echo "LLVM_CONFIG_EXECUTABLE=${env:LLVM_INSTALL_PREFIX}\\bin\\llvm-config"
          echo "MinicondaRoot=${env:MinicondaRoot}"
          echo "PythonRoot=${env:PythonRoot}"
          echo "PythonLibDir=${env:PythonLibDir}"
          echo "PythonExecutable=${env:PythonExecutable}"
          echo "CondaExecutable=${env:MinicondaRoot}\\condabin\\conda"
          echo "PipExecutable=${env:PythonExecutable}"